name: "tagged-release-aws"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  tagged-release-aws:
    name: "Tagged Release AWS only"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      #- name: Test
      #  run: go build -v && go test ./...
      - name: Build for linux/amd64
        run: go run build/main.go aws -o terraformer-aws-linux-amd64
      #- name: Build for linux/arm64
      #  run: GOOS=linux GOARCH=arm64 go run build/main.go aws -o terraformer-aws-linux-arm64
      - name: Build for mac
        run: GOOS=darwin GOARCH=amd64 go run build/main.go aws -o terraformer-aws-darwin-amd64
      #- name: Build for mac Apple Silicon
      #  run: GOOS=darwin GOARCH=arm64 go run build/main.go -o terraformer-aws-darwin-arm64
      #- name: Build for windows
      #  run: GOOS=windows go run bild/main.go aws -o terraformer-aws-windows-amd64
      #- name: Build for all providers
      #  run: go run build/multi-build/main.go

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.event.inputs.version }}
          prerelease: false
          files: |
            terraformer-*
